add new riscv-arch-test RISCOF
howardlau1999/yatcpu pull request #42
Opened 2022-07-25 23:18 UTC by Tiger9Tu

添加了新测试框架RISCOF的模块，运行方式会在今天同步更新到yatcpu-docs。

2022-07-26 08:22 UTC, howardlau1999 requested changes

2022-07-26 08:22 UTC, howardlau1999 commented on riscof-target/config.ini
> +yatcpubin=/home/tuyue/git-repos/tmp/yatcpu/verilog/verilator/obj_dir
这些路径看看是不是可以用参数形式配置？写死不太好

2022-08-04 10:26 UTC, Tiger9Tu commented
config.ini用相对路径，同时添加了riscof github action

2022-08-04 10:28 UTC, howardlau1999 commented
修改一下.gitignore，把 `__pycache__` 排除掉

2022-08-04 11:04 UTC, Tiger9Tu commented
添加pycache和riscof_work（riscof产生的临时文件）到.gitignore

2022-08-04 11:06 UTC, merged